### ISSUE TITLE
Mass Mailing Workaround

### ISSUE THREAD

**Issue by nlargebiz** [opencats/OpenCATS#326]
Hi.

This issue has been created more as an informational about how to work around the mailing system not working in 0.9.3-3 for me.  Essentially the problem is that when selecting one or more candidates from the list of candidiates under the candidates tab, and then using Action -> "Send Email" to send a mass mailing the merge fields (Eg. Candidate Name, known as %CANDFULLNAME%) are not replaced with the actual opencats data (in this case the candidate full name, so the text "%CANDFULLNAME%" appears instead.

After some deliberation my team decided to go with an eMail Merge in GMail which seems to work.  For this reason I am adding this issue in the hope that a user seeing the same behavior could see this as a good alternative to the intended behavior of opencats.

The link describing how to accomplish this eMail Merge can be found at the following link...

[here](https://support.office.com/en-us/article/Use-mail-merge-to-send-bulk-email-messages-0f123521-20ce-4aa8-8b62-ac211dedefa4)

Thanks in advance.  Nick.

**Comment by cptr13** [comment]
I'm honestly not even sure if this is legit.  But please elaborate on how this helps.

**Comment by nlargebiz** [comment]
The option to Export data in the "Action" submenu will allow the user to export the data to csv format.  That exported file is then used to generate the mail merge by following the steps provided by Microsoft in the link I posted.  This provides a way of doing a personalized e-mail merge if your currently installed version of the opencats system does not implement as intended.

I hope this clarifies the problem and solution.

Nick.

**Comment by cptr13** [comment]
Yes actually thanks. Not only that, but I will put it on the documentation to-do list! Excellent thought! Thank you!

**Comment by skrchnavy** [comment]
#231 shall implement requested feature. waiting to be approved / merged into develop and included in a next release.
